// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXjL-Hh9pD2tVaxoPQW6Et-cAuYlFURQ',
    appId: '1:771316915553:web:f6b5f07e236b1cc392b920',
    messagingSenderId: '771316915553',
    projectId: 'fanitt-89fc4',
    authDomain: 'fanitt-89fc4.firebaseapp.com',
    storageBucket: 'fanitt-89fc4.firebasestorage.app',
    measurementId: 'G-T9R8Q6WJJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3w6SkE0g0Iw0A-UB4EU66fB33z-OSCac',
    appId: '1:771316915553:android:9356ba98e6312a0592b920',
    messagingSenderId: '771316915553',
    projectId: 'fanitt-89fc4',
    storageBucket: 'fanitt-89fc4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSktK3vxhgyICNL-7LbMCSSdPkLhNZF90',
    appId: '1:771316915553:ios:60ba7c7a2664a9d192b920',
    messagingSenderId: '771316915553',
    projectId: 'fanitt-89fc4',
    storageBucket: 'fanitt-89fc4.firebasestorage.app',
    androidClientId: '771316915553-6amkae1v06tkjat9mq6h96slr062702t.apps.googleusercontent.com',
    iosClientId: '771316915553-v1oi4gq2qnnvsbfkfphboui7ki39d3ss.apps.googleusercontent.com',
    iosBundleId: 'fanitt.comapp.fanittapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSktK3vxhgyICNL-7LbMCSSdPkLhNZF90',
    appId: '1:771316915553:ios:60ba7c7a2664a9d192b920',
    messagingSenderId: '771316915553',
    projectId: 'fanitt-89fc4',
    storageBucket: 'fanitt-89fc4.firebasestorage.app',
    androidClientId: '771316915553-6amkae1v06tkjat9mq6h96slr062702t.apps.googleusercontent.com',
    iosClientId: '771316915553-v1oi4gq2qnnvsbfkfphboui7ki39d3ss.apps.googleusercontent.com',
    iosBundleId: 'fanitt.comapp.fanittapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZXjL-Hh9pD2tVaxoPQW6Et-cAuYlFURQ',
    appId: '1:771316915553:web:7e01adf1d4061c1992b920',
    messagingSenderId: '771316915553',
    projectId: 'fanitt-89fc4',
    authDomain: 'fanitt-89fc4.firebaseapp.com',
    storageBucket: 'fanitt-89fc4.firebasestorage.app',
    measurementId: 'G-767GCES2Q0',
  );
}
